** 模块化配置
*** init.el 配置
init.el 保持最小配置，其他功能都拆分到独立文件。
加载 lisp directory path，在 init.el 里面添加:
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/init.el
  ;; -*- coding: utf-8; lexical-binding: t; -*-

  ;; open for debug error when you need.
  ;;(setq debug-on-error t)

  (add-to-list 'load-path "~/.emacs.d/lisp/")
  (require 'init-begin)
  (require 'init-package)
  (require 'init-keybinding)
  (require 'init-basic)
  (require 'init-completion)
  (require 'init-awesome-tab)
  (require 'init-search)
  (require 'init-ui)
  (require 'init-org)
  (require 'init-evil)


  (setq custom-file (expand-file-name "~/.emacs.d/lisp/custom.el"))
  (load custom-file 'no-error 'no-message)

#+END_SRC
*** init-begin.el
#+begin_src  emacs-lisp :tangle ~/.emacs.d/lisp/init-begin.el
  ;; hidden menu-bar tool-bar scroll-bar, not nil ,not negative, specially apply in client mode.

  (push '(menu-bar-lines . 0) default-frame-alist)
  (push '(tool-bar-lines . 0) default-frame-alist)
  (push '(vertical-scroll-bars) default-frame-alist)

  ;; full screen emacs
  (toggle-frame-fullscreen)
  (provide 'init-begin)
#+end_src
*** init-packages.el package 相关配置
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-package.el

  (require 'package)
  (setq package-archives '(("gnu"   . "https://mirrors.163.com/elpa/gnu/")
			   ("melpa" . "https://mirrors.163.com/elpa/melpa/")))
  ;; add nongnu resource
  (add-to-list 'package-archives
	      (cons "nongnu" (format "http%s://elpa.nongnu.org/nongnu/"
				     (if (gnutls-available-p) "s" ""))))

  (package-initialize)

  ;;防止反复调用 package-refresh-contents 会影响加载速度
  (when (not package-archive-contents)
    (package-refresh-contents))

  ;;; 这个配置一定要配置在 use-package 的初始化之前，否则无法正常安装
  (assq-delete-all 'org package--builtins)
  (assq-delete-all 'org package--builtin-versions)


  ;; Setup `use-package'
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  ;; 重启命令
  (use-package restart-emacs
    :ensure t)

  ;;添加本地目录插件
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/site-lisp/awesome-tab") )


  (provide 'init-package)
#+END_SRC

*** init-keybinding.el

Emacs 常见符号的意义如下：
M(eta)：统一改到 option 键
s(uper)：统一改到 command 键
S(Shift)：不用修改
C(trl)：统一改成 Caps Lock

光标的移动在编辑器里面最为常见，必须熟练使用这些操作。
C-f 为前移一个字符， f 代表 forward。
C-b 为后移一个字符， b 代表 backward。
C-p 为上移至前一行， p 代表 previous。
C-n 为上移至下一行， n 代表 next。
C-a 为移至行首， a 代表 ahead。
C-e 为移至行尾， e 代表 end。

在整个Mac系统都内置了这些快捷键。在很多应用里也是。

把mac的几个常用操作配置到Emacs里面。

#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-keybinding.el
;; -*- lexical-binding: t -*-

  ;; mac option key ->  meta
  ;; mac commad key -> super
  (setq mac-option-modifier 'meta
	mac-command-modifier 'super)

  (global-set-key (kbd "s-a") 'mark-whole-buffer) ;;对应Windows上面的Ctrl-a 全选
  (global-set-key (kbd "s-c") 'kill-ring-save) ;;对应Windows上面的Ctrl-c 复制
  (global-set-key (kbd "s-s") 'save-buffer) ;; 对应Windows上面的Ctrl-s 保存
  (global-set-key (kbd "s-v") 'yank) ;对应Windows上面的Ctrl-v 粘贴
  (global-set-key (kbd "s-z") 'undo) ;对应Windows上面的Ctrol-z 撤销
  (global-set-key (kbd "s-x") 'kill-region) ;对应Windows上面的Ctrol-x 剪切

  (provide 'init-keybinding)

#+END_SRC
  
*** init-basic.el
查看 emacs 的帮助可以：
C-h k 寻找快捷键的帮助信息
C-h v 寻找变量的帮助信息
C-h f 寻找函数的帮助信息
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-basic.el
  ;; -*- lexical-binding: t -*-

  ;; emacs >= 26  开启行号可以这么设置
  (display-line-numbers-mode 1)

  ;; 关闭工具栏，tool-bar-mode 即为一个 Minor Mode
  (tool-bar-mode -1)
  ;; 关闭文件滑动控件
  (scroll-bar-mode -1)
  ;; 更改光标的样式
  (setq-default cursor-type 'bar)

  ;;不再需要，下面有更好的补全插件
  ;;(icomplete-mode 1)

  ;; 快速打开配置文件
  (defun open-init-file()
    (interactive)
    (find-file "~/.emacs.d/init-v2.org"))
  ;; 这一行代码，将函数 open-init-file 绑定到 <f2> 键上
  (global-set-key (kbd "<f2>") 'open-init-file)

  ;; 更改显示字体大小 16pt
  ;; http://stackoverflow.com/questions/294664/how-to-set-the-font-size-in-emacs
  (set-face-attribute 'default nil :height 160);;

  ;;让鼠标滚动更好用
  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1) ((control) . nil)))
  (setq mouse-wheel-progressive-speed nil)

  ;;括号匹配高亮
  (show-paren-mode t)
  ;;自动补全成对的符号
  (electric-pair-mode 1)


  ;;禁止自动生成备份文件
  (setq make-backup-files nil)

  ;;最近打开文件
  (require 'recentf)
  (recentf-mode 1)
  (setq recentf-max-menu-item 8)
  (global-set-key (kbd "C-x b") 'consult-buffer)

  (delete-selection-mode 1)

  ;;高亮当前行
  (global-hl-line-mode 1)

  ;; 自动加载在外部修改的文件
  (global-auto-revert-mode 1)

  ;; close auto save
  (setq auto-save-default nil)
  ;;关闭错误的时候哔哔的警告声音
  (setq ring-bell-function 'ignore)
  ;; simple to y or n
  (fset 'yes-or-no-p 'y-or-n-p)

  (setq inhibit-splash-screen t)
  (setq initial-scratch-message ";; Happy Hacking! Emacs loves you!")

  ;;内置 package
  ;;保存命令历史，在emacs重启之后，能够智能提示最近的操作命令，否则重启之后都清空了
  (use-package savehist
    :hook (after-init . savehist-mode)
    :init (setq enable-recursive-minibuffers t ; Allow commands in minibuffers
	      history-length 1000
	      savehist-additional-variables '(mark-ring
					      global-mark-ring
					      search-ring
					      regexp-search-ring
					      extended-command-history)
	      savehist-autosave-interval 300)
  )

  ;;内置package
  (use-package saveplace
    :hook (after-init . save-place-mode))


  (provide 'init-basic)


#+END_SRC

*** init-completion.el
company config
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-completion.el

  (use-package company
    :ensure t
    :bind (:map company-active-map
		("C-n" . 'company-select-next)
		("C-p" . 'company-select-previous))
    :init
    (global-company-mode t)
    :config
    (setq company-minimum-prefix-length 1)
    (setq company-idle-delay 0))


#+END_SRC

vertico config
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-completion.el
  ;;增强 minibuffer 补全
  (use-package vertico :ensure	t)
  (vertico-mode t)

  ;; make c-j/c-k work in vertico selection
  (define-key vertico-map (kbd "C-j") 'vertico-next)
  (define-key vertico-map (kbd "C-k") 'vertico-previous)


#+END_SRC

orderless config
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-completion.el
  ;;在 minibuffer 支持模糊搜索
  (use-package orderless :ensure t)
  (setq completion-styles '(orderless))

#+END_SRC

marginalia config
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-completion.el
  ;; 增强 minibuffer 的annotation
  (use-package marginalia :ensure t)
  (marginalia-mode t)

#+END_SRC

embark config
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-completion.el
  ;; minibuffer action 就类似于在任何内容上右键点击
  (use-package embark :ensure t)
  (global-set-key (kbd "C-;") 'embark-act)
  ;;利用这个 可以不用再记忆快捷键，只需要执行 C-x C-h 呼出帮助命令
  ;;然后输入想执行命令的关键字，既可以出现提示列表，又因为 orderless
  ;; 可以不用在意关键字单词的顺序 最后直接回车执行即可
  (setq prefix-help-command 'embark-prefix-help-command)

#+END_SRC

consult config

增强 consult 和 embark ，强大的文件夹内搜索大杀器
使用 consult-ripgrep 命令可以调用 ripgrep 搜索目标目录。

consult-ripgrep 可以搜索当前目录下所有文件内容，而且给出一个候选列表。
这时候按 C-c C-e 调用 embark-export-write 函数，将候选列表写入一下可写 buffer，
这时候再按 M-x query-replace-regexp 则可以交互式替换文本内容。 按 y 则执行替换，按 n 跳过
最后 C-x C-s 保存所有替换结果。
这个功能可以替换 ivy 插件。

consult-find 可以搜索当前目录下所有文件内容。
C-c p f 查找 project 下的指定文件
consult-recent-file 列出最近使用文件.


#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-completion.el
  ;;增强文件内搜索和跳转函数定义
  (use-package consult :ensure t)
  ;;同时使用需要这个
  (use-package embark-consult :ensure t)
  ;;强大的文件内搜索功能，完全替代了 swiper 插件
  (global-set-key (kbd "C-s") 'consult-line)
  ;;文件内函数跳转
  ;;consult-imenu

  ;; consult 默认配置优化
  (eval-after-load 'consult
  (progn
    (setq
     consult-narrow-key "<"
     consult-line-numbers-widen t
     consult-async-min-input 2
     consult-async-refresh-delay  0.15
     consult-async-input-throttle 0.2
     consult-async-input-debounce 0.1)
    ))


#+END_SRC

使用 Emacs 打开文件管理器
M-x consult-directory-externally 然后输入文件目录，既可以用系统文件浏览器打开该目录
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-completion.el

  (defun consult-directory-externally (file)
    "Open FILE externally using the default application of the system."
    (interactive "fOpen externally: ")
    (if (and (eq system-type 'windows-nt)
	     (fboundp 'w32-shell-execute))
	(shell-command-to-string (encode-coding-string (replace-regexp-in-string "/" "\\\\"
										 (format "explorer.exe %s" (file-name-directory (expand-file-name file)))) 'gbk))
      (call-process (pcase system-type
		      ('darwin "open")
		      ('cygwin "cygstart")
		      (_ "xdg-open"))
		    nil 0 nil
		    (file-name-directory (expand-file-name file)))))
  ;; 给 embark 添加一个 action: E 使用系统的文件浏览器打开当前目录
  ;; https://github.com/oantolin/embark/tree/fcf068c0e912baa9267cbec02e56a5972d8f31b4#creating-your-own-keymaps
  (eval-after-load 'embark
    (defvar-keymap embark-file-map "E" #'consult-directory-externally))
  ;;打开当前文件的目录
  (defun my-open-current-directory ()
    (interactive)
    (consult-directory-externally default-directory))



  (provide 'init-completion)
#+END_SRC

*** init-awesome-tab.el
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-awesome-tab.el
  ;; -*- lexical-binding: t -*-
  (require 'awesome-tab)
  (awesome-tab-mode t)

  (defun awesome-tab-buffer-groups ()
    "`awesome-tab-buffer-groups' control buffers' group rules.

  Group awesome-tab with mode if buffer is derived from `eshell-mode' `emacs-lisp-mode' `dired-mode' `org-mode' `magit-mode'.
  All buffer name start with * will group to \"Emacs\".
  Other buffer group by `awesome-tab-get-group-name' with project name."
    (list
     (cond
      ((or (string-equal "*" (substring (buffer-name) 0 1))
	   (memq major-mode '(magit-process-mode
			      magit-status-mode
			      magit-diff-mode
			      magit-log-mode
			      magit-file-mode
			      magit-blob-mode
			      magit-blame-mode
			      )))
       "Emacs")
      ((derived-mode-p 'eshell-mode)
       "EShell")
      ((derived-mode-p 'emacs-lisp-mode)
       "Elisp")
      ((derived-mode-p 'dired-mode)
       "Dired")
      ((memq major-mode '(org-mode org-agenda-mode diary-mode))
       "OrgMode")
      (t
       (awesome-tab-get-group-name (current-buffer))))))


  (provide 'init-awesome-tab)
#+END_SRC

*** init-search.el
增强 consult 和 embark ，强大的文件夹内搜索大杀器
使用 consult-ripgrep 命令可以调用 ripgrep 搜索目标目录。

consult-ripgrep 可以搜索当前目录下所有文件内容，而且给出一个候选列表。
这时候按 C-c C-e 调用 embark-export-write 函数，将候选列表写入一下可写 buffer，
这时候再按 M-x query-replace-regexp 则可以交互式替换文本内容。 按 y 则执行替换，按 n 跳过
最后 C-x C-s 保存所有替换结果。
这个功能可以替换 ivy 插件。


#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-search.el

  (use-package embark-consult :ensure t)
  (use-package wgrep :ensure t)
  (setq wgrep-auto-save-buffer t)

  (eval-after-load
      'consult
    '(eval-after-load
	 'embark
       '(progn
	  (require 'embark-consult)
	  (add-hook
	   'embark-collect-mode-hook
	   #'consult-preview-at-point-mode))))

  (defun embark-export-write ()
  "Export the current vertico results to a writable buffer if possible.
  Supports exporting consult-grep to wgrep, file to wdeired, and consult-location to occur-edit"
  (interactive)
  (require 'embark)
  (require 'wgrep)
  (pcase-let ((`(,type . ,candidates)
	       (run-hook-with-args-until-success 'embark-candidate-collectors)))
    (pcase type
      ('consult-grep (let ((embark-after-export-hook #'wgrep-change-to-wgrep-mode))
		       (embark-export)))
      ('file (let ((embark-after-export-hook #'wdired-change-to-wdired-mode))
	       (embark-export)))
      ('consult-location (let ((embark-after-export-hook #'occur-edit-mode))
			   (embark-export)))
      (x (user-error "embark category %S doesn't support writable export" x)))))

  (define-key minibuffer-local-map (kbd "C-c C-e") 'embark-export-write)


  (provide 'init-search)
#+END_SRC	  

*** init-ui.el
#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-ui.el
  ;; -*- lexical-binding: t -*-
  ;; install theme
  (use-package gruvbox-theme :ensure t)
  (load-theme 'gruvbox-light-soft t)
  (use-package doom-modeline
    :ensure t
    ;;fix doom modeline for org TODO/agenda
    :custom-face
    (mode-line ((t (:height 0.9))))
    (mode-line-inactive ((t (:height 0.9))))
    :init
    (doom-modeline-mode t))
  (use-package simple
    :ensure nil
    :hook (after-init . size-indication-mode)
    :init
    (progn
      (setq column-number-mode t)
      ))

  ;; M-x nerd-icons-install-fonts 安装必要的字体，否则有些字符不显示
  (use-package nerd-icons
    :ensure t
    ;; :custom
    ;; The Nerd Font you want to use in GUI
    ;; "Symbols Nerd Font Mono" is the default and is recommended
    ;; but you can use any other Nerd Font if you want
    ;; (nerd-icons-font-family "Symbols Nerd Font Mono")
    )



  (provide 'init-ui)

#+END_SRC
*** init-org.el
**** org TODO
每日计划 daily routine 比如
    Daily Routine [%]
     - [ ] coding
     - [ ] reading
     - [ ] exercise
在 Daily Routine 上按 C-c C-s 选择日期，输入具体时间，并且在生成的时间后面添加 1d,可以使得 checklist 设置每日自动生成。
通过勾选checklist 完成所以的任务，然后使用 C-c C-t 标记今天日程完成，那么 SCHEDULED 会自动把日期 +1
但是 checklist 还是已经勾选了，使用 org-checklist package, 然后在 Daily Routine 按 M-x org-set-properties, 为日程设置属性
:RESET_CHECK_BOXES: true
就可以自动更新为未勾选的 checklist

同时设置 org-log-done 可以将已经完成的日程收到完成的列表: LOGBOOK ，支持收缩和展开

**** org agenda
**** org capture

#+BEGIN_SRC emacs-lisp  :tangle ~/.emacs.d/lisp/init-org.el
  ;;安装最新版本 org 不使用内置版本
  (use-package org
    :pin gnu
    :ensure t)

  (use-package org-contrib
    :pin nongnu
    :ensure t)

  (require 'org-tempo)  ;开启easy template

  ;; 需要开启 electric-pair-mode
  ;; 禁用左尖括号
  (setq electric-pair-inhibit-predicate
	`(lambda (c)
	   (if (char-equal c ?\<) t (,electric-pair-inhibit-predicate c))))

  (add-hook 'org-mode-hook
	    (lambda ()
	      (setq-local electric-pair-inhibit-predicate
			  `(lambda (c)
			     (if (char-equal c ?\<) t (,electric-pair-inhibit-predicate c))))))
  ;; 更丰富的 TODO 状态
  (setq org-todo-keywords
      (quote ((sequence "TODO(t)" "STARTED(s)" "|" "DONE(d!/!)")
	      (sequence "WAITING(w@/!)" "SOMEDAY(S)" "|" "CANCELLED(c@/!)" "MEETING(m)" "PHONE(p)"))))
  (require 'org-checklist)
  ;; need repeat task and properties
  (setq org-log-done t)
  (setq org-log-into-drawer t)

  ;; C-c C-s schedule
  ;; C-c C-d deadline
  (global-set-key (kbd "C-c a") 'org-agenda)
  (setq org-agenda-files '("~/org/gtd.org"))
  (setq org-agenda-span 'day)


  (provide 'init-org)
#+END_SRC

*** 使用 use-package
use-package 实际上是一个宏，更好的取代 require 的方式，该宏允许你以一种既面向性能又整洁的方式隔离文件中的包配置。
更安全的 require ，如果加载 package 失败，require 会终止整个程序，而 use-pacakge 则只是在 message 中给出警告。
如果 package 不存在，则安装 package （使用 ensure 关键字）。
集中化配置，use-pacage 支持 init,config,autoload,bind 等关键字，方便管理加载包过程中的一些配置。
init 的代码在包加载之前执行，config 代码在包加载后执行，commands 可以在真正需要这个包时再加载, 提高启动速度, 避免无谓的 require.
bind 用于绑定快捷键。
*** init-evil.el
#+begin_src emacs-lisp  :tangle ~/.emacs.d/lisp/init-evil.el
  (use-package evil
    :ensure t
    :init
    ;; 不使用 evil 自带的 keybinding 
    (setq evil-want-keybinding nil)
    ;; 使用 vim 的 C-u 滚动界面操作
    ;; C-d C-u 向前翻页 向后翻页
    (setq evil-want-C-u-scroll t)
    (evil-mode)

    ;; https://emacs.stackexchange.com/questions/46371/how-can-i-get-ret-to-follow-org-mode-links-when-using-evil-mode
    (with-eval-after-load 'evil-maps
      (define-key evil-motion-state-map (kbd "RET") nil))

    ;; insert state 不使用 vi keybinding
    (setcdr evil-insert-state-map nil)
    (define-key evil-insert-state-map [escape] 'evil-normal-state)

    (define-key evil-normal-state-map (kbd "[ SPC") (lambda () (interactive) (evil-insert-newline-above) (forward-line)))
    (define-key evil-normal-state-map (kbd "] SPC") (lambda () (interactive) (evil-insert-newline-below) (forward-line -1)))


    (define-key evil-normal-state-map (kbd "[ b") 'previous-buffer)
    (define-key evil-normal-state-map (kbd "] b") 'next-buffer)
    (define-key evil-motion-state-map (kbd "[ b") 'previous-buffer)
    (define-key evil-motion-state-map (kbd "] b") 'next-buffer)

    (evil-define-key 'normal dired-mode-map
      (kbd "<RET>") 'dired-find-alternate-file
      (kbd "C-k") 'dired-up-directory
      "`" 'dired-open-term
      "q" 'quit-window
      "o" 'dired-find-file-other-window
      ")" 'dired-omit-mode)


    )

  ;; 支持 vim 的 redo undo ，而且更强大
  ;; u undo  C-r redo
  (use-package undo-tree
    :ensure t
    :diminish
    :init
    (global-undo-tree-mode 1)
    (setq undo-tree-auto-save-history nil)
    (evil-set-undo-system 'undo-tree))

  ;;文本搜索  doom modeline 会显示结果总数以及当前 index
  (use-package evil-anzu
    :ensure t
    :after evil
    :diminish
    :demand t
    :init
    (global-anzu-mode t))

  ;;社区更统一的定义各种常用 mode 下的 evil state
  (use-package evil-collection
    :ensure t
    :demand t
    :config
    (setq evil-collection-mode-list (remove 'lispy evil-collection-mode-list))
    (evil-collection-init)

    (cl-loop for (mode . state) in
	     '((org-agenda-mode . normal)
	       (Custom-mode . emacs)
	       (eshell-mode . emacs)
	       (org-mode . emacs)
	       (makey-key-mode . motion))
	     do (evil-set-initial-state mode state)))

  ;; vim surround plugin
  (use-package evil-surround
    :ensure t
    :init
    (global-evil-surround-mode 1))

  (use-package evil-nerd-commenter
    :ensure t
    :init
    (define-key evil-normal-state-map (kbd ",/") 'evilnc-comment-or-uncomment-lines)
    (define-key evil-visual-state-map (kbd ",/") 'evilnc-comment-or-uncomment-lines)
    )
  (use-package evil-snipe
    :ensure t
    :diminish
    :init
    (evil-snipe-mode +1)
    (evil-snipe-override-mode +1))

  ;; 按 % 跳转到匹配的符号，比如 () {} 甚至 begin end
  (use-package evil-matchit
    :ensure
    :init
    (global-evil-matchit-mode 1))

  ;; emacs 也有 multicusor 但是类 vim 的这个 iedit 操作更符合 vim 习惯
  ;; 在 normal 模式按 vim 选择当前 word，按 R 则会选择文本中所有的该 word
  ;; 此时可以按 gg 或者 G 跳转到匹配的 word 第一个 或者最后一个
  ;; 或者 0 $ 跳转到 word 的第一个单词/最后一个单词
  (use-package iedit
    :ensure t
    :init
    (setq iedit-toggle-key-default nil)
    :config
    (define-key iedit-mode-keymap (kbd "M-h") 'iedit-restrict-function)
    (define-key iedit-mode-keymap (kbd "M-i") 'iedit-restrict-current-line))

  (use-package evil-multiedit
    :ensure t
    :commands (evil-multiedit-default-keybinds)
    :init
    (evil-multiedit-default-keybinds))



  (provide 'init-evil)
#+end_src


vi 的各种模式 mode ，在 evil 中称为 state。
normal state 
insert state
emacs state 排除所有的 vi binding 回到 Emacs 的默认行为，通过 C-z 切换。
visual state
motion state 对只读 buffer 的一种模式。只能 motion 不能修改。
replace state 与 insert state 类似，除了是 replace 而不是 insert 。
operator-pending state



